### ISSUE TITLE
[Suggestion] Dynamic Prices.

### ISSUE THREAD

**Issue by RafaelGamerBr49** [promcteam/BossShopPro#36] opened 2023-09-09 22:09 UTC
Hey, is there any plan for dynamic prices soon? Because, at the moment, there are only paid plugins with this functionality, and it would be really interesting to have this functionality in this plugin. 

If there is no plan to add such functionality yet, here are some ideas: the ability to use values ​​that influence globally, by store, or on a specific item, in addition to being able to use percentages or integer values.

**Comment by MaksyKun** [comment] 2024-03-16 19:01
As this Issue provides a more detailed approach, Ill close this here as a duplicate of #53

**Closed** 2024-03-16 19:02 UTC
